import { Command } from 'commander';
import path from 'node:path';
import fs from 'fs-extra';
import kleur from 'kleur';

// ── YAML helpers (no runtime dep — hand-written serialiser for tiny GHA files) ─

function indent(text: string, n: number) {
  const pad = ' '.repeat(n);
  return text
    .split('\n')
    .map((l) => (l.trim() === '' ? '' : pad + l))
    .join('\n');
}

// ── Template builders ─────────────────────────────────────────────────────────

/**
 * .github/workflows/ci.yml
 *
 * Runs lint + typecheck + unit tests on every push/PR.
 * Detects affected packages via `mfjs ci affected` and only builds those.
 */
function buildCiWorkflow(opts: { nodeVersion: string; packageManager: string }): string {
  return `# Generated by \`mfjs ci generate\` — modify freely.
name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  NODE_VERSION: '${opts.nodeVersion}'

jobs:
  # ── Lint + Typecheck + Unit Tests ──────────────────────────────────────────
  quality:
    name: Quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history for affected detection

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: '${opts.packageManager}'

      - name: Install dependencies
        run: ${opts.packageManager} install --frozen-lockfile

      - name: Type-check all packages
        run: ${opts.packageManager} exec mfjs typecheck

      - name: Run unit tests
        run: ${opts.packageManager} test

  # ── Affected Builds ────────────────────────────────────────────────────────
  build:
    name: Build affected apps
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: '${opts.packageManager}'

      - name: Install dependencies
        run: ${opts.packageManager} install --frozen-lockfile

      - name: Detect & build affected apps
        run: |
          AFFECTED=\$(${opts.packageManager} exec mfjs ci affected --format=json --base=HEAD~1)
          echo "Affected: \$AFFECTED"
          if [ "\$AFFECTED" = "[]" ]; then
            echo "No affected apps — skipping build."
            exit 0
          fi
          ${opts.packageManager} exec mfjs build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: apps/*/dist
          if-no-files-found: ignore
`;
}

/**
 * .github/workflows/pr-preview.yml
 *
 * Deploys a per-PR preview to Netlify (or any static host supporting deploy previews).
 * Requires:
 *   NETLIFY_AUTH_TOKEN — in repo secrets
 *   NETLIFY_SITE_ID   — in repo secrets
 */
function buildPreviewWorkflow(opts: { nodeVersion: string; packageManager: string }): string {
  return `# Generated by \`mfjs ci generate\` — modify freely.
# Requires secrets: NETLIFY_AUTH_TOKEN, NETLIFY_SITE_ID
name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '${opts.nodeVersion}'

jobs:
  preview:
    name: Deploy PR preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: '${opts.packageManager}'

      - name: Install dependencies
        run: ${opts.packageManager} install --frozen-lockfile

      - name: Build all apps
        run: ${opts.packageManager} exec mfjs build
        env:
          NODE_ENV: production

      - name: Deploy to Netlify (preview)
        id: deploy
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./apps/shell/dist
          production-deploy: false
          github-token: \${{ secrets.GITHUB_TOKEN }}
          deploy-message: "PR #\${{ github.event.number }} preview"
          alias: pr-\${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: \${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: \${{ secrets.NETLIFY_SITE_ID }}

      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const url = '\${{ steps.deploy.outputs.deploy-url }}';
            if (!url) return;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: \`🚀 **Preview deployed:** [\${url}](\${url})\`
            });
`;
}

/**
 * .github/workflows/deploy.yml
 *
 * Deploys the shell dist to a CDN (Netlify / S3+CloudFront / Azure Static Web Apps).
 * Triggered on push to main; requires matching secrets.
 */
function buildDeployWorkflow(opts: {
  nodeVersion: string;
  packageManager: string;
  target: 'netlify' | 's3' | 'azure';
}): string {
  const deployStep =
    opts.target === 'netlify'
      ? `      - name: Deploy to Netlify (production)
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./apps/shell/dist
          production-deploy: true
          github-token: \${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from \${{ github.sha }}"
        env:
          NETLIFY_AUTH_TOKEN: \${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: \${{ secrets.NETLIFY_SITE_ID }}`
      : opts.target === 's3'
        ? `      - name: Deploy to S3 + CloudFront
        run: |
          aws s3 sync apps/shell/dist s3://\${{ secrets.S3_BUCKET }}/shell --delete
          aws cloudfront create-invalidation \\
            --distribution-id \${{ secrets.CF_DISTRIBUTION_ID }} \\
            --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: \${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: \${{ secrets.AWS_REGION }}`
        : `      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: \${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: \${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: apps/shell/dist
          skip_app_build: true`;

  return `# Generated by \`mfjs ci generate\` — modify freely.
name: Deploy

on:
  push:
    branches: [main, master]

env:
  NODE_VERSION: '${opts.nodeVersion}'

jobs:
  deploy:
    name: Build & deploy to CDN (${opts.target})
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: '${opts.packageManager}'

      - name: Install dependencies
        run: ${opts.packageManager} install --frozen-lockfile

      - name: Build all apps (production)
        run: ${opts.packageManager} exec mfjs build
        env:
          NODE_ENV: production

${deployStep}
`;
}

// ── mfjs ci generate ──────────────────────────────────────────────────────────

const generateSubCommand = new Command('generate')
  .description(
    'Scaffold GitHub Actions workflow files for CI, CD, and PR previews'
  )
  .option('-d, --dir <path>', 'Workspace root directory', process.cwd())
  .option('--node <version>', 'Node.js version to use in workflows', '22')
  .option(
    '--package-manager <pm>',
    'Package manager (pnpm | npm | yarn)',
    'pnpm'
  )
  .option(
    '--deploy-target <target>',
    'CDN target for deploy workflow: netlify | s3 | azure',
    'netlify'
  )
  .option('--no-preview', 'Skip generating the PR preview workflow')
  .option('--no-deploy', 'Skip generating the deploy workflow')
  .action(
    async (opts: {
      dir: string;
      node: string;
      packageManager: string;
      deployTarget: string;
      preview: boolean;
      deploy: boolean;
    }) => {
      const workspaceDir = path.resolve(opts.dir);
      const workflowsDir = path.join(workspaceDir, '.github', 'workflows');

      await fs.ensureDir(workflowsDir);

      const baseOpts = {
        nodeVersion: opts.node,
        packageManager: opts.packageManager,
      };

      // ci.yml — always generated
      const ciPath = path.join(workflowsDir, 'ci.yml');
      await fs.outputFile(ciPath, buildCiWorkflow(baseOpts), 'utf8');
      console.log(kleur.green('✓') + ' ' + kleur.gray(path.relative(workspaceDir, ciPath)));

      if (opts.preview) {
        const previewPath = path.join(workflowsDir, 'pr-preview.yml');
        await fs.outputFile(previewPath, buildPreviewWorkflow(baseOpts), 'utf8');
        console.log(
          kleur.green('✓') + ' ' + kleur.gray(path.relative(workspaceDir, previewPath))
        );
      }

      if (opts.deploy) {
        const target = opts.deployTarget as 'netlify' | 's3' | 'azure';
        const deployPath = path.join(workflowsDir, 'deploy.yml');
        await fs.outputFile(
          deployPath,
          buildDeployWorkflow({ ...baseOpts, target }),
          'utf8'
        );
        console.log(
          kleur.green('✓') + ' ' + kleur.gray(path.relative(workspaceDir, deployPath))
        );
      }

      console.log(kleur.cyan('\nCI/CD workflows generated.'));
      console.log(
        kleur.gray(
          'Edit .github/workflows/ and add the required secrets to your GitHub repo.\n' +
            'Required secrets per workflow:\n' +
            '  ci.yml       — none\n' +
            '  pr-preview   — NETLIFY_AUTH_TOKEN, NETLIFY_SITE_ID\n' +
            '  deploy.yml   — depends on --deploy-target (see file comments)'
        )
      );
    }
  );

// ── mfjs ci affected ─────────────────────────────────────────────────────────

type AppMeta = {
  name: string;
  type: 'host' | 'remote';
  port: number;
};

async function discoverApps(
  workspaceDir: string
): Promise<Array<{ dir: string; meta: AppMeta }>> {
  const appsDir = path.join(workspaceDir, 'apps');
  if (!(await fs.pathExists(appsDir))) return [];

  const folders = (await fs.readdir(appsDir)).filter((f) => !f.startsWith('.'));
  const result: Array<{ dir: string; meta: AppMeta }> = [];

  for (const folder of folders) {
    const appDir = path.join(appsDir, folder);
    const metaPath = path.join(appDir, 'mfjs.app.json');
    if (!(await fs.pathExists(metaPath))) continue;
    const meta = (await fs.readJson(metaPath)) as AppMeta;
    result.push({ dir: appDir, meta });
  }

  return result;
}

/**
 * Returns the list of apps whose source files have changed between `base` and
 * `head` (defaults to staged + unstaged changes when base is not provided).
 *
 * Strategy: for each app directory, check if `git diff --name-only <base> <head>`
 * returns any path that starts with `apps/<name>/` or `libs/`.
 * Any lib change is considered to affect ALL apps.
 */
export async function detectAffectedApps(
  workspaceDir: string,
  base = 'HEAD~1',
  head = 'HEAD'
): Promise<string[]> {
  const { spawnSync } = await import('node:child_process');

  const result = spawnSync(
    'git',
    ['diff', '--name-only', base, head],
    { cwd: workspaceDir, encoding: 'utf8' }
  );

  const changedFiles: string[] =
    result.status === 0
      ? (result.stdout ?? '')
            .split('\n')
            .map((l: string) => l.trim())
            .filter(Boolean)
      : [];

  const apps = await discoverApps(workspaceDir);

  // If any lib changed → all apps are potentially affected
  const libChanged = changedFiles.some(
    (f) => f.startsWith('libs/') || f.startsWith('packages/')
  );
  if (libChanged) return apps.map((a) => a.meta.name);

  const affected: string[] = [];
  for (const app of apps) {
    const prefix = `apps/${app.meta.name}/`;
    if (changedFiles.some((f) => f.startsWith(prefix))) {
      affected.push(app.meta.name);
    }
  }

  return affected;
}

const affectedSubCommand = new Command('affected')
  .description(
    'List apps affected by changes between two git refs (used in CI to skip unaffected builds)'
  )
  .option('-d, --dir <path>', 'Workspace root directory', process.cwd())
  .option('--base <ref>', 'Base git ref to diff from', 'HEAD~1')
  .option('--head <ref>', 'Head git ref to diff to', 'HEAD')
  .option(
    '--format <fmt>',
    'Output format: text (default) or json',
    'text'
  )
  .action(
    async (opts: { dir: string; base: string; head: string; format: string }) => {
      const workspaceDir = path.resolve(opts.dir);
      const affected = await detectAffectedApps(workspaceDir, opts.base, opts.head);

      if (opts.format === 'json') {
        process.stdout.write(JSON.stringify(affected) + '\n');
        return;
      }

      if (affected.length === 0) {
        console.log(kleur.yellow('No affected apps detected.'));
        return;
      }

      console.log(kleur.cyan('Affected apps:'));
      for (const name of affected) {
        console.log('  ' + kleur.white(name));
      }
    }
  );

// ── mfjs ci preview (alias for generate --no-deploy) ─────────────────────────

const previewSubCommand = new Command('preview')
  .description('Scaffold only the PR preview workflow (.github/workflows/pr-preview.yml)')
  .option('-d, --dir <path>', 'Workspace root directory', process.cwd())
  .option('--node <version>', 'Node.js version', '22')
  .option('--package-manager <pm>', 'Package manager', 'pnpm')
  .action(
    async (opts: { dir: string; node: string; packageManager: string }) => {
      const workspaceDir = path.resolve(opts.dir);
      const workflowsDir = path.join(workspaceDir, '.github', 'workflows');
      await fs.ensureDir(workflowsDir);

      const previewPath = path.join(workflowsDir, 'pr-preview.yml');
      await fs.outputFile(
        previewPath,
        buildPreviewWorkflow({ nodeVersion: opts.node, packageManager: opts.packageManager }),
        'utf8'
      );
      console.log(
        kleur.green('✓ PR preview workflow → ') +
          kleur.gray(path.relative(workspaceDir, previewPath))
      );
    }
  );

// ── mfjs ci (parent) ──────────────────────────────────────────────────────────

export const ciCommand = new Command('ci')
  .description('CI/CD automation: generate workflows, detect affected apps, scaffold previews')
  .addCommand(generateSubCommand)
  .addCommand(affectedSubCommand)
  .addCommand(previewSubCommand);

// ── Exported helpers (used by tests + e2e) ────────────────────────────────────

export { buildCiWorkflow, buildPreviewWorkflow, buildDeployWorkflow };
