import { Command } from 'commander';
import path from 'node:path';
import fs from 'fs-extra';
import kleur from 'kleur';
import { buildCiWorkflow, buildPreviewWorkflow, buildDeployWorkflow } from './ci.js';

async function writeJson(filePath: string, obj: unknown) {
  await fs.outputFile(filePath, JSON.stringify(obj, null, 2) + '\n', 'utf8');
}

async function writeText(filePath: string, content: string) {
  await fs.outputFile(filePath, content, 'utf8');
}

async function ensureEmptyDir(dir: string) {
  const exists = await fs.pathExists(dir);
  if (!exists) return;

  const entries = await fs.readdir(dir);
  // Allow creating into an existing empty directory.
  if (entries.length === 0) return;

  throw new Error(`Target directory is not empty: ${dir}`);
}

export const initCommand = new Command('init')
  .description('Initialize a new MFJS workspace (monorepo)')
  .argument('<name>', 'Folder name for the new workspace')
  .option('-d, --dir <path>', 'Parent directory to create the workspace in', process.cwd())
  .action(async (name: string, opts: { dir: string }) => {
    const workspaceDir = path.resolve(opts.dir, name);

    console.log(kleur.cyan(`Creating MFJS workspace in ${workspaceDir}`));

    await ensureEmptyDir(workspaceDir);
    await fs.ensureDir(workspaceDir);

    // root package.json
    await writeJson(path.join(workspaceDir, 'package.json'), {
      name,
      private: true,
      packageManager: 'pnpm@9.15.5',
      scripts: {
        dev: 'pnpm -r --parallel dev',
        build: 'pnpm -r build',
        test: 'pnpm -r test',
        typecheck: 'mfjs typecheck',
        'ci:affected': 'mfjs ci affected',
      },
    });

    // pnpm workspace
    await writeText(
      path.join(workspaceDir, 'pnpm-workspace.yaml'),
      'packages:\n  - "packages/*"\n  - "apps/*"\n  - "libs/*"\n\n'
    );

    // README
    await writeText(
      path.join(workspaceDir, 'README.md'),
      `# ${name}\n\nGenerated by @mfjs/cli.\n`
    );

    // mfjs.config.json
    await writeJson(path.join(workspaceDir, 'mfjs.config.json'), {
      $schema: 'https://mfjs.dev/schemas/mfjs.config.json',
      appsDir: 'apps',
      libsDir: 'libs',
    });

    // mfjs.config.ts
    await writeText(
      path.join(workspaceDir, 'mfjs.config.ts'),
      [
        'export type MfjsConfig = {',
        '  appsDir: string;',
        '  libsDir: string;',
        '  remotes?: Record<string, { url: string }>;',
        '};',
        '',
        'const config: MfjsConfig = {',
        "  appsDir: 'apps',",
        "  libsDir: 'libs',",
        '};',
        '',
        'export default config;',
        '',
      ].join('\n')
    );

    // Strict shared TypeScript base config
    await writeJson(path.join(workspaceDir, 'tsconfig.base.json'), {
      $schema: 'https://json.schemastore.org/tsconfig',
      compilerOptions: {
        target: 'ES2022',
        module: 'ES2022',
        moduleResolution: 'Bundler',
        declaration: true,
        declarationMap: true,
        sourceMap: true,
        strict: true,
        noUncheckedIndexedAccess: true,
        exactOptionalPropertyTypes: true,
        noImplicitOverride: true,
        noImplicitReturns: true,
        noFallthroughCasesInSwitch: true,
        noPropertyAccessFromIndexSignature: true,
        forceConsistentCasingInFileNames: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
    });

    // .gitignore
    await writeText(
      path.join(workspaceDir, '.gitignore'),
      [
        'node_modules',
        'dist',
        '.cache',
        '*.local',
        '.env',
        '.env.*',
        '!.env.example',
        'playwright-report',
        'test-results',
        '',
      ].join('\n')
    );

    // GitHub Actions CI/CD workflows
    const workflowsDir = path.join(workspaceDir, '.github', 'workflows');
    await fs.ensureDir(workflowsDir);
    const wfOpts = { nodeVersion: '22', packageManager: 'pnpm' };
    await writeText(path.join(workflowsDir, 'ci.yml'), buildCiWorkflow(wfOpts));
    await writeText(path.join(workflowsDir, 'pr-preview.yml'), buildPreviewWorkflow(wfOpts));
    await writeText(
      path.join(workflowsDir, 'deploy.yml'),
      buildDeployWorkflow({ ...wfOpts, target: 'netlify' })
    );

    console.log(kleur.green('Done.'));
    console.log(kleur.gray('Next:'));
    console.log(kleur.gray('  mfjs generate host shell'));
    console.log(kleur.gray('  mfjs generate remote dashboard'));
    console.log(kleur.gray('  mfjs dev'));
  });
