import { Command } from 'commander';
import path from 'node:path';
import fs from 'fs-extra';
import kleur from 'kleur';

type AppMeta = {
  name: string;
  type: 'host' | 'remote';
  port: number;
};

export type PageRoute = {
  /** Route pathname relative to app base, e.g. "/" or "/reports/:id" */
  path: string;
  /** Source file path, relative to app root */
  file: string;
};

export type AppRoutesManifest = {
  app: string;
  basePath: string;
  routes: PageRoute[];
};

export type HostRoutesManifest = {
  host: string;
  routes: Array<{ path: string; remote: string; module: string }>;
};

function toPosixPath(p: string) {
  return p.replace(/\\/g, '/');
}

async function findApps(workspaceDir: string) {
  const appsDir = path.join(workspaceDir, 'apps');
  if (!(await fs.pathExists(appsDir))) return [];

  const folders = (await fs.readdir(appsDir)).filter((f) => !f.startsWith('.'));
  const apps: Array<{ dir: string; meta: AppMeta }> = [];

  for (const folder of folders) {
    const dir = path.join(appsDir, folder);
    const metaPath = path.join(dir, 'mfjs.app.json');
    if (!(await fs.pathExists(metaPath))) continue;
    const meta = (await fs.readJson(metaPath)) as AppMeta;
    apps.push({ dir, meta });
  }

  return apps;
}

function routeFromPageFile(relFromPages: string) {
  // pages/index.tsx -> /
  // pages/about.tsx -> /about
  // pages/reports/[id].tsx -> /reports/:id
  // pages/docs/[...slug].tsx -> /docs/*
  // pages/settings/index.tsx -> /settings

  let withoutExt = relFromPages.replace(/\.(tsx|ts|jsx|js)$/, '');
  withoutExt = withoutExt.replace(/\\/g, '/');

  const segs = withoutExt.split('/').filter(Boolean);

  const out: string[] = [];
  for (let i = 0; i < segs.length; i++) {
    const s = segs[i];
    if (s === undefined) continue;
    if (s === 'index' && i === segs.length - 1) continue;

    const mCatchAll = s.match(/^\[\.\.\.(.+)\]$/);
    if (mCatchAll) {
      out.push('*');
      continue;
    }

    const mParam = s.match(/^\[(.+)\]$/);
    if (mParam) {
      out.push(':' + mParam[1]);
      continue;
    }

    out.push(s);
  }

  return '/' + out.join('/');
}

async function scanPages(appDir: string) {
  const pagesDir = path.join(appDir, 'src', 'pages');
  if (!(await fs.pathExists(pagesDir))) return [];

  const files: string[] = [];
  const walk = async (dir: string) => {
    const entries = await fs.readdir(dir);
    for (const e of entries) {
      const abs = path.join(dir, e);
      const st = await fs.stat(abs);
      if (st.isDirectory()) await walk(abs);
      else if (/\.(tsx|ts|jsx|js)$/.test(e)) files.push(abs);
    }
  };

  await walk(pagesDir);

  return files
    .map((abs) => {
      const relFromPages = path.relative(pagesDir, abs);
      const relFromApp = toPosixPath(path.relative(appDir, abs));
      return { path: routeFromPageFile(relFromPages), file: relFromApp };
    })
    .sort((a, b) => a.path.localeCompare(b.path));
}

function sortRoutesForMatching(routes: PageRoute[]) {
  // Heuristic: more specific routes first.
  // Static > params > splat, and longer paths first.
  const score = (p: string) => {
    const segs = p.split('/').filter(Boolean);
    let s = 0;
    for (const seg of segs) {
      if (seg === '*') s += 0;
      else if (seg.startsWith(':')) s += 1;
      else s += 2;
    }
    return s * 100 + segs.length;
  };

  return [...routes].sort((a, b) => score(b.path) - score(a.path));
}

async function writeRemoteRoutesModule(appDir: string, routes: PageRoute[]) {
  const outFile = path.join(appDir, 'src', 'mfjs.routes.ts');
  const lines: string[] = [];

  lines.push('// THIS FILE IS AUTO-GENERATED by `mfjs routes`.');
  lines.push('// It exposes the remote\'s file-based route table for the host to consume.');
  lines.push("import type { RemotePageRoute } from '@mfjs/runtime';");
  lines.push('');
  lines.push('export const pages: RemotePageRoute[] = [');

  const sorted = sortRoutesForMatching(routes);
  for (const r of sorted) {
    // Keep the import target relative to this file (src/mfjs.routes.ts).
    // Page files live under src/pages/** so we should import from './pages/**'.
    const rel = toPosixPath(r.file).replace(/^\.\//, '');
    const importTarget = rel.startsWith('src/pages/')
      ? './' + rel.slice('src/'.length)
      : rel.startsWith('pages/')
        ? './' + rel
        : rel.startsWith('src/')
          ? './' + rel.slice('src/'.length)
          : './' + rel;
    lines.push(
      `  { path: ${JSON.stringify(r.path)}, load: () => import(${JSON.stringify(importTarget)}) },`
    );
  }

  lines.push('];');
  lines.push('');
  lines.push('export default pages;');
  lines.push('');

  await fs.outputFile(outFile, lines.join('\n'), 'utf8');
}

export const routesCommand = new Command('routes')
  .description('Generate file-based routing manifests from apps/*/src/pages')
  .option('-d, --dir <path>', 'Workspace root directory', process.cwd())
  .action(async (opts: { dir: string }) => {
    const workspaceDir = path.resolve(opts.dir);
    const apps = await findApps(workspaceDir);

    if (apps.length === 0) {
      console.log(kleur.yellow('No apps found (missing apps/*/mfjs.app.json).'));
      return;
    }

    const host = apps.find((a) => a.meta.type === 'host');
    const remotes = apps.filter((a) => a.meta.type === 'remote');

    // Per-app manifests
    for (const app of apps) {
      const basePath = app.meta.type === 'host' ? '/' : `/${app.meta.name}`;
      const routes = await scanPages(app.dir);
      const manifest: AppRoutesManifest = { app: app.meta.name, basePath, routes };
      const outPath = path.join(app.dir, 'mfjs.routes.json');
      await fs.outputFile(outPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
      console.log(kleur.green(`wrote ${path.relative(workspaceDir, outPath)}`));

      // For remotes, also emit an importable route table module.
      if (app.meta.type === 'remote') {
        await writeRemoteRoutesModule(app.dir, routes);
        console.log(kleur.green(`wrote ${path.relative(workspaceDir, path.join(app.dir, 'src/mfjs.routes.ts'))}`));
      }
    }

    // Host route table for mounting remotes
    if (host) {
      const defaultRemote = remotes[0];
      const hostRouteTable: HostRoutesManifest = {
        host: host.meta.name,
        routes: [
          ...(defaultRemote ? [{ path: '/', remote: defaultRemote.meta.name, module: './App' }] : []),
          ...remotes.map((r) => ({ path: `/${r.meta.name}/*`, remote: r.meta.name, module: './App' })),
        ],
      };
      const outPath = path.join(host.dir, 'mfjs.routes.host.json');
      await fs.outputFile(outPath, JSON.stringify(hostRouteTable, null, 2) + '\n', 'utf8');
      console.log(kleur.green(`wrote ${path.relative(workspaceDir, outPath)}`));
    }

    console.log(kleur.cyan('Done. Next: update your host to load mfjs.routes.host.json and mount remotes based on the URL.'));
  });
