import { Command } from 'commander';
import path from 'node:path';
import fs from 'fs-extra';
import kleur from 'kleur';

const SW_SOURCE = `/* generated by \`mfjs sw generate\` — MFJS offline cache */
const CACHE = 'mfjs-v1';
const REMOTE_CACHE = 'mfjs-remotes-v1';
const APP_SHELL = ['/', '/index.html'];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(APP_SHELL).catch(() => undefined)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE && k !== REMOTE_CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (/remoteEntry\\.js$/.test(url.pathname) || /\\/mfjs\\/remotes\\//.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(REMOTE_CACHE, req));
    return;
  }
  if (/\\.[a-f0-9]{8,}\\.(js|css|woff2?|png|svg|jpg|jpeg|webp)$/.test(url.pathname)) {
    event.respondWith(cacheFirst(CACHE, req));
    return;
  }
  if (req.destination === 'document' || req.headers.get('accept')?.includes('text/html')) {
    event.respondWith(networkFirst(CACHE, req));
  }
});

async function cacheFirst(name, req) {
  const cache = await caches.open(name);
  const hit = await cache.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok) cache.put(req, res.clone());
  return res;
}

async function networkFirst(name, req) {
  const cache = await caches.open(name);
  try {
    const res = await fetch(req);
    if (res.ok) cache.put(req, res.clone());
    return res;
  } catch {
    const hit = await cache.match(req);
    if (hit) return hit;
    return cache.match('/') || Response.error();
  }
}

async function staleWhileRevalidate(name, req) {
  const cache = await caches.open(name);
  const hit = await cache.match(req);
  const fetchPromise = fetch(req).then((res) => {
    if (res.ok) cache.put(req, res.clone());
    return res;
  }).catch(() => hit);
  return hit || fetchPromise;
}
`;

export const swCommand = new Command('sw').description('Service Worker helpers (offline shell + cached remoteEntry).');

swCommand
  .command('generate')
  .description('Write mfjs-sw.js into a host app public/ folder.')
  .option('--app <name>', 'Host app name', 'shell')
  .option('--cwd <dir>', 'Workspace root', process.cwd())
  .option('--force', 'Overwrite if exists')
  .action(async (opts: { app: string; cwd: string; force?: boolean }) => {
    const cwd = path.resolve(opts.cwd);
    const dir = path.join(cwd, 'apps', opts.app, 'public');
    const target = path.join(dir, 'mfjs-sw.js');
    if (!(await fs.pathExists(path.dirname(dir)))) {
      console.error(kleur.red(`sw: app "${opts.app}" not found at apps/${opts.app}`));
      process.exit(1);
    }
    await fs.ensureDir(dir);
    if ((await fs.pathExists(target)) && !opts.force) {
      console.log(kleur.yellow(`skip — ${path.relative(cwd, target)} exists (use --force)`));
      return;
    }
    await fs.writeFile(target, SW_SOURCE, 'utf8');
    console.log(kleur.green(`wrote ${path.relative(cwd, target)}`));
    console.log(kleur.dim('register in your bootstrap:'));
    console.log(kleur.dim(`  import { registerMfjsServiceWorker } from '@mfjs/runtime';`));
    console.log(kleur.dim(`  registerMfjsServiceWorker({ url: '/mfjs-sw.js' });`));
  });
