export interface ServiceWorkerRegisterOptions {
  /** URL to the SW script. Default: '/mfjs-sw.js'. */
  url?: string;
  /** Scope. Default: '/'. */
  scope?: string;
  /** Enable registration. Default: process.env.NODE_ENV === 'production'. */
  enabled?: boolean;
  /** Called when a new SW is waiting to activate. */
  onUpdateReady?: (registration: ServiceWorkerRegistration) => void;
  /** Called when the SW first takes control. */
  onReady?: (registration: ServiceWorkerRegistration) => void;
  /** Auto-skip waiting when an update is ready. Default: false. */
  autoActivate?: boolean;
}

export async function registerMfjsServiceWorker(
  opts: ServiceWorkerRegisterOptions = {},
): Promise<ServiceWorkerRegistration | null> {
  if (typeof window === 'undefined') return null;
  if (!('serviceWorker' in navigator)) return null;
  const g = globalThis as { process?: { env?: Record<string, string | undefined> } };
  const enabled = opts.enabled ?? (g.process?.env?.['NODE_ENV'] === 'production');
  if (!enabled) return null;

  const url = opts.url ?? '/mfjs-sw.js';
  const scope = opts.scope ?? '/';

  try {
    const reg = await navigator.serviceWorker.register(url, { scope });

    if (reg.waiting && opts.onUpdateReady) opts.onUpdateReady(reg);

    reg.addEventListener('updatefound', () => {
      const installing = reg.installing;
      if (!installing) return;
      installing.addEventListener('statechange', () => {
        if (installing.state === 'installed' && navigator.serviceWorker.controller) {
          if (opts.autoActivate) installing.postMessage({ type: 'SKIP_WAITING' });
          opts.onUpdateReady?.(reg);
        }
      });
    });

    await navigator.serviceWorker.ready;
    opts.onReady?.(reg);
    return reg;
  } catch (err) {
    console.warn('[mfjs] service worker registration failed', err);
    return null;
  }
}

export async function unregisterMfjsServiceWorker(): Promise<boolean> {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return false;
  const regs = await navigator.serviceWorker.getRegistrations();
  let ok = true;
  for (const r of regs) ok = (await r.unregister()) && ok;
  return ok;
}

/** Inline SW script source — bundlers can emit via `import sw from './mfjs-sw-source?raw'`. */
export const MFJS_SERVICE_WORKER_SOURCE = `/* generated by @mfjs/runtime */
const CACHE = 'mfjs-v1';
const REMOTE_CACHE = 'mfjs-remotes-v1';
const APP_SHELL = ['/', '/index.html'];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(APP_SHELL).catch(() => undefined)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE && k !== REMOTE_CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // remoteEntry.js and federation chunks → stale-while-revalidate
  if (/remoteEntry\\.js$/.test(url.pathname) || /\\/mfjs\\/remotes\\//.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(REMOTE_CACHE, req));
    return;
  }

  // Fingerprinted assets → cache-first
  if (/\\.[a-f0-9]{8,}\\.(js|css|woff2?|png|svg|jpg|jpeg|webp)$/.test(url.pathname)) {
    event.respondWith(cacheFirst(CACHE, req));
    return;
  }

  // HTML documents → network-first with offline fallback
  if (req.destination === 'document' || req.headers.get('accept')?.includes('text/html')) {
    event.respondWith(networkFirst(CACHE, req));
    return;
  }
});

async function cacheFirst(name, req) {
  const cache = await caches.open(name);
  const hit = await cache.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok) cache.put(req, res.clone());
  return res;
}

async function networkFirst(name, req) {
  const cache = await caches.open(name);
  try {
    const res = await fetch(req);
    if (res.ok) cache.put(req, res.clone());
    return res;
  } catch {
    const hit = await cache.match(req);
    if (hit) return hit;
    return cache.match('/') || Response.error();
  }
}

async function staleWhileRevalidate(name, req) {
  const cache = await caches.open(name);
  const hit = await cache.match(req);
  const fetchPromise = fetch(req).then((res) => {
    if (res.ok) cache.put(req, res.clone());
    return res;
  }).catch(() => hit);
  return hit || fetchPromise;
}
`;
