/**
 * @mfjs/types — App config + app metadata types.
 */

// ── App metadata ─────────────────────────────────────────────────────────────

/** Role of an application in the MFJS workspace. */
export type AppType = 'host' | 'remote';

/**
 * Contents of `mfjs.app.json` — the per-app metadata file generated by
 * `mfjs generate host|remote`.
 */
export type MfjsAppConfig = {
  /** App name (used as the Module Federation container name). */
  name: string;
  /** Whether this app is the host shell or a remote micro-frontend. */
  type: AppType;
  /** Dev server port. */
  port: number;
  /**
   * Exposed modules map (`"./App": "./src/remote.tsx"`).
   * Only meaningful on remote apps.
   */
  exposes?: Record<string, string>;
  /**
   * Additional shared packages to declare as singletons beyond the defaults.
   */
  shared?: string[];
};
