import Link from 'next/link';
import { Callout } from '@/components/docs/callout';

export const metadata = {
  title: 'Production checklist',
  description:
    'Pre-launch checklist for MOXJS apps. Security, observability, performance, reliability, deploy, release process.',
};

interface CheckItem {
  task: string;
  hint?: string;
  href?: string;
}

interface CheckGroup {
  category: string;
  blurb: string;
  tasks: CheckItem[];
}

const groups: CheckGroup[] = [
  {
    category: 'Security',
    blurb:
      'Federation increases the trust surface — untrusted remotes, hydration payloads, and CDN tampering are all in play. Lock each one down before going live.',
    tasks: [
      {
        task: 'Content-Security-Policy header set on every HTML response (buildCsp)',
        hint: 'Use strict-dynamic + a base64url nonce per response. Loose CSPs are worse than none.',
        href: '/docs/security',
      },
      {
        task: 'SRI integrity attribute on every remoteEntry.js script tag',
        hint: 'Generated by federation.sri.algo = "sha384". Block-on-mismatch in production.',
        href: '/docs/security',
      },
      {
        task: 'RemoteAllowlist wired to getRemoteRegistry',
        hint: 'Reject URLs outside the configured origins — defense in depth even with SRI.',
      },
      {
        task: 'All inline state serialized via safeJsonForScript or serializeState',
        hint: 'Both escape </script>, line-separator (U+2028) and paragraph-separator (U+2029).',
      },
      { task: 'HTTPS only — HSTS header emitted with includeSubDomains + preload' },
      { task: 'CORS restricted to known origins (no wildcard in prod)' },
      { task: 'Secrets stored in the platform secret manager — never in .env checked in' },
      { task: 'Rate limiting on auth endpoints (@moxjs/security rate-limit)' },
    ],
  },
  {
    category: 'Observability',
    blurb:
      'When a remote fails, the host blinks but the failure must be obvious to oncall. Wire metrics + errors before launch, not after the first incident.',
    tasks: [
      {
        task: 'Error reporting adapter installed (Sentry / Rollbar / OTel)',
        href: '/docs/observability',
      },
      { task: 'collectWebVitals() called in the shell bootstrap' },
      { task: 'Structured logger writing JSON to a collector' },
      {
        task: 'Alerts configured for error rate, p95 LCP, remote-load error rate',
        hint: 'Set the threshold above noise but below user-visible degradation.',
      },
      { task: 'onRemoteLoad telemetry feeds the same RUM pipeline as page metrics' },
      { task: 'Source maps uploaded to the error tracker (gated behind the build hash)' },
      { task: '@moxjs/cli version printed in every error report (audit trail)' },
    ],
  },
  {
    category: 'Performance',
    blurb:
      'Each remote pays a network round-trip on first load. Budget it, monitor it, and reject regressions in CI.',
    tasks: [
      { task: 'moxjs perf budgets green in CI' },
      { task: 'Bundle analyzer (moxjs analyze) reviewed before each release' },
      {
        task: 'Remote preload tags in SSR head (remoteEntryPreloads)',
        href: '/docs/concurrent-preload',
      },
      {
        task: 'Cache-Control tuned per route (cacheControl helper)',
        hint: 'Immutable for hashed assets; short max-age for HTML; SWR for remote manifests.',
      },
      { task: 'Assets hashed and served with immutable cache-control' },
      { task: 'Compression (gzip + brotli) enabled at the edge' },
      { task: 'Image derivatives generated for every breakpoint (moxjs image)' },
      { task: 'Fonts preloaded with crossorigin=anonymous' },
    ],
  },
  {
    category: 'Reliability',
    blurb:
      'A remote crash should be a tile-level failure, not a page-level failure. Boundaries, health checks, fallbacks.',
    tasks: [
      {
        task: 'Health check endpoint per remote',
        hint: 'fetchHealth() can gate a load — fast-fail beats a 30s timeout.',
      },
      { task: 'RemoteRegistry fetches manifest with retry + exponential backoff' },
      { task: 'Error boundary around every RemoteOutlet' },
      { task: 'Version mismatch warnings surfaced in logs (checkRuntimeVersions)' },
      { task: 'Graceful fallback UI when a remote fails to load' },
      { task: 'Blue/green or weighted-remote rollout for risky changes' },
      { task: 'Service Worker offline fallback page tested end-to-end' },
    ],
  },
  {
    category: 'Deploy',
    blurb:
      'Production parity matters — the staging environment should diverge in data, not in topology.',
    tasks: [
      {
        task: 'Adapter scaffolded (Vercel / Cloudflare / Node / Docker)',
        href: '/docs/deployment',
      },
      { task: 'CDN publicPath set in moxjs.config.ts' },
      { task: 'Preview deploy per PR (moxjs ci affected)' },
      { task: 'Rollback plan documented and rehearsed' },
      { task: 'Smoke tests run against the deploy URL before flipping DNS' },
      { task: 'CDN cache purged on release (or version-namespaced URLs)' },
    ],
  },
  {
    category: 'Release process',
    blurb:
      'Predictable releases need predictable artifacts. Changesets + SemVer + tags carry the audit trail.',
    tasks: [
      { task: 'Changesets workflow on main' },
      { task: 'SemVer for every published package' },
      { task: 'CHANGELOG.md per package up to date' },
      { task: 'Git tags for each release' },
      { task: 'Linked packages bump together: [runtime, ssr, security] etc.' },
      { task: 'Release notes posted to the team channel before flipping flags' },
    ],
  },
];

export default function Checklist() {
  return (
    <>
      <h1>Production checklist</h1>
      <p>
        Before flipping the DNS, confirm every item below. Items link to the feature that
        implements them. Copy this list into your release-readiness doc and sign off item by item.
      </p>

      <Callout variant="warn" title="Anything unchecked is a launch blocker">
        Don&apos;t treat the checklist as aspirational. Each item exists because skipping it has
        cost a production incident somewhere. If a check doesn&apos;t apply to your shape, write
        down why and move on; don&apos;t silently skip.
      </Callout>

      {groups.map((group) => (
        <section key={group.category}>
          <h2 id={group.category.toLowerCase().replace(/\s+/g, '-')}>{group.category}</h2>
          <p>{group.blurb}</p>
          <ul>
            {group.tasks.map((t) => (
              <li key={t.task}>
                {t.href ? (
                  <Link href={t.href}>{t.task}</Link>
                ) : (
                  <span>{t.task}</span>
                )}
                {t.hint ? <span className="text-muted-foreground"> — {t.hint}</span> : null}
              </li>
            ))}
          </ul>
        </section>
      ))}

      <h2 id="release-day">Release-day runbook</h2>
      <ol>
        <li>
          <strong>T-24h:</strong> changeset PR merged. CI green. Preview deploy hit by team for
          smoke checks.
        </li>
        <li>
          <strong>T-1h:</strong> announce in the team channel. Page the on-call to standby. Roll
          forward the feature flag to <em>off-for-everyone</em>.
        </li>
        <li>
          <strong>T-0:</strong> tag the release. CI publishes packages + deploys the host + each
          remote. Wait for the deploy job to complete.
        </li>
        <li>
          <strong>T+5m:</strong> run smoke tests against production URLs. Confirm error rate flat,
          LCP flat, remote-load error rate &lt; baseline.
        </li>
        <li>
          <strong>T+10m:</strong> flip the feature flag to 10%. Watch the dashboards.
        </li>
        <li>
          <strong>T+30m:</strong> if metrics are clean, ramp to 50%. Otherwise revert.
        </li>
        <li>
          <strong>T+60m:</strong> ramp to 100%. Close the release ticket. Post a summary with
          deltas in error rate, LCP, and bundle size.
        </li>
      </ol>

      <h2 id="rollback">Rollback plan</h2>
      <ol>
        <li>
          <strong>Feature-flag revert</strong> first if the issue is gated. Sub-minute mitigation.
        </li>
        <li>
          <strong>Deploy revert</strong> — re-deploy the previous tag via the platform UI. ~3 min.
        </li>
        <li>
          <strong>CDN cache purge</strong> if the issue is a stale chunk. The SW will pick up the
          new bytes on next visit; for in-session users, broadcast a refresh prompt.
        </li>
        <li>
          <strong>Hotfix</strong> only if revert isn&apos;t an option. Branch from the released
          tag, cherry-pick the fix, ship through the same pipeline.
        </li>
      </ol>
    </>
  );
}
