// THIS FILE IS AUTO-GENERATED by `mfjs routes`.
// It exposes the remote's file-based route table for the host to consume.
import type { RemotePageRoute } from '@mfjs/runtime';

export const pages: RemotePageRoute[] = [
];

export default pages;
