import { CodeBlock } from '@/components/site/code-block';
import { Callout } from '@/components/docs/callout';

export const metadata = {
  title: 'Nested routes',
  description:
    'Parent/child route trees with Outlet slots. Lazy chunks, ancestor params, code-collocated layouts.',
};

export default function NestedRoutes() {
  return (
    <>
      <h1>Nested routes</h1>
      <p>
        <code>NestedRouter</code> renders a parent/child route tree with React-Router-v6-style{' '}
        <code>Outlet</code> slots. Each layer picks up its own params; unmatched tails render the
        nearest <code>noMatch</code>. Use it inside a remote when its own UI needs layout
        composition — header/sidebar/main shells, tab containers, master-detail views.
      </p>

      <Callout variant="info" title="Nested vs. file-based routing">
        <code>NestedRouter</code> is a <em>declarative</em> tree (you write JSX). The file-based
        <code> moxjs.routes.ts</code> generated by <code>moxjs routes</code> is a flat list. Use
        nested routing when you need shared layouts; use file-based routing for catalog pages.
        They compose — drop a <code>RemoteApp</code> inside an outlet, or a{' '}
        <code>NestedRouter</code> inside a page.
      </Callout>

      <h2 id="define">Define the tree</h2>
      <CodeBlock
        language="tsx"
        code={`import { NestedRouter, Outlet, type NestedRoute } from '@moxjs/runtime';

const routes: NestedRoute[] = [
  {
    path: '/app',
    element: <AppShell />,
    children: [
      { index: true, element: <Dashboard /> },
      {
        path: 'users',
        element: <UsersLayout />,
        children: [
          { index: true, lazy: () => import('./pages/users/index.js') },
          { path: ':id', lazy: () => import('./pages/users/detail.js') },
        ],
      },
      { path: 'settings/*', lazy: () => import('./pages/settings.js') },
    ],
  },
];

export default function Root() {
  return <NestedRouter routes={routes} fallback={<Spinner />} notFound={<NotFound />} />;
}

function AppShell() {
  return (
    <div className="app-shell">
      <Sidebar />
      <main><Outlet /></main>
    </div>
  );
}`}
      />

      <h2 id="index">Index routes</h2>
      <p>
        Mark a child with <code>index: true</code> to render when the parent path matches exactly.
        Only one index per children array. Index routes do not contribute a URL segment — they
        decide what shows up at the parent&apos;s URL.
      </p>

      <h2 id="lazy">Lazy layouts</h2>
      <p>
        Any route can ship <code>lazy: () =&gt; import(...)</code> instead of <code>element</code>.
        The module default export becomes the layout/page. React Suspense shows{' '}
        <code>fallback</code> while the chunk loads. Use lazy for everything except the smallest
        cross-cutting shells (sidebar, top nav) so the initial bundle stays minimal.
      </p>

      <h2 id="params">Params from ancestors</h2>
      <p>
        <code>useOutletParams</code> reads the cumulative params from every ancestor segment, not
        just the deepest. Nested <code>:userId</code> + <code>:postId</code> are both available in
        the deepest component.
      </p>
      <CodeBlock
        language="tsx"
        code={`import { useOutletParams } from '@moxjs/runtime';

function UserDetail() {
  const params = useOutletParams<{ id: string }>();
  return <h1>User {params.id}</h1>;
}`}
      />

      <h2 id="route-shape">Route shape</h2>
      <table>
        <thead>
          <tr>
            <th>Key</th>
            <th>Type</th>
            <th>Purpose</th>
          </tr>
        </thead>
        <tbody>
          <tr><td><code>path</code></td><td><code>string</code></td><td>Pattern with <code>:param</code> / <code>*</code> splat. Required unless <code>index: true</code>.</td></tr>
          <tr><td><code>index</code></td><td><code>boolean</code></td><td>Match when the parent path is hit exactly. Mutually exclusive with <code>path</code>.</td></tr>
          <tr><td><code>element</code></td><td><code>ReactNode</code></td><td>Eager render. Use for cheap shells (sidebar, header).</td></tr>
          <tr><td><code>lazy</code></td><td><code>() =&gt; Promise&lt;{'{ default: ComponentType }'}&gt;</code></td><td>Code-split chunk. Suspense fallback = parent <code>NestedRouter</code> <code>fallback</code>.</td></tr>
          <tr><td><code>children</code></td><td><code>NestedRoute[]</code></td><td>Sub-routes rendered into <code>&lt;Outlet /&gt;</code>.</td></tr>
          <tr><td><code>guards</code></td><td><code>RouteGuard[]</code></td><td>Run before render. Falsy blocks; <code>{'{ redirect }'}</code> redirects.</td></tr>
          <tr><td><code>errorElement</code></td><td><code>ReactNode</code></td><td>Boundary for this subtree — replaces the default error UI.</td></tr>
          <tr><td><code>handle</code></td><td><code>unknown</code></td><td>Arbitrary metadata — e.g. breadcrumb labels, tab IDs, analytics tags.</td></tr>
        </tbody>
      </table>

      <h2 id="error">Error boundaries</h2>
      <p>
        Add <code>errorElement</code> to any route to isolate failures to that subtree. A child
        crash bubbles up to the nearest <code>errorElement</code> ancestor, leaving the rest of the
        shell intact.
      </p>
      <CodeBlock
        language="tsx"
        code={`const routes: NestedRoute[] = [
  {
    path: '/dashboard',
    element: <DashboardShell />,
    errorElement: <DashboardError />,           // failures here keep the global header
    children: [
      { index: true, lazy: () => import('./Overview.js') },
      { path: 'reports/*', lazy: () => import('./reports/Router.js'), errorElement: <ReportsError /> },
    ],
  },
];`}
      />

      <h2 id="handle">Route metadata via <code>handle</code></h2>
      <p>
        Walk the matched route chain to build breadcrumbs, sidebars, analytics tags. Each
        route&apos;s <code>handle</code> field is opaque — define your own convention.
      </p>
      <CodeBlock
        language="tsx"
        code={`const routes: NestedRoute[] = [
  {
    path: '/billing',
    element: <BillingShell />,
    handle: { breadcrumb: 'Billing' },
    children: [
      { path: 'invoices/:id', element: <Invoice />, handle: { breadcrumb: 'Invoice' } },
    ],
  },
];

import { useMatchedRoutes } from '@moxjs/runtime';

function Breadcrumbs() {
  const matched = useMatchedRoutes<{ breadcrumb: string }>();
  return (
    <nav>
      {matched.map((m, i) => <span key={i}>{m.handle.breadcrumb}</span>)}
    </nav>
  );
}`}
      />

      <h2 id="resolve-chain">Resolving outside React</h2>
      <p>
        Need to know what would render at a path without mounting it? Use{' '}
        <code>resolveChain</code> — useful for prefetching ancestor chunks or server-side
        authorization checks.
      </p>
      <CodeBlock
        language="ts"
        code={`import { resolveChain } from '@moxjs/runtime';

const chain = resolveChain(routes, '/app/users/42');
// → [
//   { route: routes[0],            params: {} },
//   { route: routes[0].children[1], params: {} },
//   { route: routes[0].children[1].children[1], params: { id: '42' } },
// ]
//
// chain.at(-1).params.id === '42'`}
      />

      <h2 id="interop">Interop with federated remotes</h2>
      <p>
        Put <code>RemoteOutlet</code> inside a layout element. The nested router owns the chrome,
        the remote owns a subtree. Both coexist because they read the same{' '}
        <code>usePathname</code> stream.
      </p>
      <CodeBlock
        language="tsx"
        code={`const routes: NestedRoute[] = [
  {
    path: '/app',
    element: <AppShell />,
    children: [
      { index: true,            element: <Dashboard /> },
      { path: 'admin/*',        element: <RemoteOutlet routes={ADMIN_ROUTES} remotes={REMOTES} /> },
      { path: 'docs/*',         lazy: () => import('./docs/Router.js') },
    ],
  },
];`}
      />

      <h2 id="ssr">SSR with nested routes</h2>
      <p>
        On the server, <code>resolveChain</code> + a sync renderer cover the same shape without
        relying on browser history. Pair with <code>renderRouteToString</code> from{' '}
        <code>@moxjs/ssr</code>:
      </p>
      <CodeBlock
        language="ts"
        code={`import { resolveChain } from '@moxjs/runtime';
import { renderRouteToString } from '@moxjs/ssr';

const chain = resolveChain(routes, new URL(request.url).pathname);
if (!chain.length) return new Response('Not Found', { status: 404 });

const html = await renderRouteToString(<NestedRouter routes={routes} />, {
  path: new URL(request.url).pathname,
});`}
      />

      <Callout variant="warn" title="Don't mount NestedRouter twice on one URL">
        Two routers writing to the same pathname is harmless (both just read the History API),
        but two routers <em>navigating</em> compete for the same <code>pushState</code>. Pick one
        as the owner per URL prefix.
      </Callout>
    </>
  );
}
